#166789953 Users Should Be Able to Login to Authors Haven
andela/ah-92explorers-frontend pull request #14
Opened 2019-08-20 16:20 UTC by Hervera

#### What does this PR do?
Logs a user to Authors Haven

#### Description of Task to be completed
- add a login route
- add login component
- validate inputs

#### How should this be manually tested?

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166789953](https://www.pivotaltracker.com/story/show/166789953)

#### Screenshots (if appropriate)

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-08-26 14:37 UTC, niyoceles requested changes

2019-08-26 14:37 UTC, niyoceles commented on src/middleware/validations/login.js
> +  } else if (pwdRegex.test(data.password) === false) {
@Hervera Kindly don't validate the password, you must return email or password is not correct.

2019-08-27 13:46 UTC, IsaiahRn approved these changes
This PR is ready to be merged

2019-08-27 13:47 UTC, elemanhillary-zz approved these changes
ready for merge

2019-08-27 13:47 UTC, niyoceles approved these changes

2019-08-27 13:52 UTC, merged