Ft login via social sites 166789954
andela/ah-92explorers-frontend pull request #17
Opened 2019-08-23 12:19 UTC by elemanhillary

#### What does this PR do?

#### Description of Task to be completed

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-08-26 07:50 UTC, Hervera requested changes
Fix the circleCI build error

2019-08-26 10:32 UTC, IsaiahRn requested changes
From the screenshot that you have provided, the twitter icon is missing.
Kindly, add that icon?

2019-08-26 10:34 UTC, IsaiahRn commented on src/__tests__/__actions__/socialLogin.spec.js
> +    //   location: {
Can you remove all these commented lines of code?

2019-08-27 07:27 UTC, Hervera requested changes
Remove conflicts

2019-08-27 10:45 UTC, kodek-sleuth requested changes

2019-08-27 10:45 UTC, kodek-sleuth commented on src/__tests__/components/social.spec.js
> +    expect(btn.length).toBe(1);
I have realised that you not actually testing what the button will do after stimulation. This is universal for All the three buttons, Please kindly indicate those tests there

2019-08-27 10:45 UTC, kodek-sleuth commented on src/components/continue/continue.js
> +import React, { Component, Fragment } from 'react';
The folder name should start with an Uppercase letter and all files with `jsx` should have the `jsx` extension. This is based on The Team Coding Conventions we signed up for

2019-08-27 12:53 UTC, elemanhillary commented on src/components/social/social.js
> +    const classNames = e.target.className.split(' ');
use a unique` id` for each of the buttons.

2019-08-27 12:53 UTC, elemanhillary commented on src/components/social/social.js
> +    const { social: redirect } = this.props;
rename to `redirectURL`

2019-08-27 12:53 UTC, elemanhillary commented on src/redux/actions/actionCreators/social.action.js
> +    const data = dec(tokenStr);
use `async/await` here

2019-08-28 08:28 UTC, niyoceles approved these changes

2019-08-28 08:29 UTC, IsaiahRn approved these changes
It can be merged

2019-08-28 08:29 UTC, Hervera approved these changes
Ready to be merged

2019-08-28 08:30 UTC, kodek-sleuth approved these changes

2019-08-28 08:31 UTC, merged