Ft create update article 166789956
andela/ah-92explorers-frontend pull request #20
Opened 2019-08-28 16:50 UTC by kodek-sleuth

#### What does this PR do?

#### Description of Task to be completed

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-08-29 04:18 UTC, Hervera requested changes
The home page is blank. The recent functionality of logout doesn't work

2019-08-29 04:24 UTC, Hervera requested changes
You disabled too many `Eslint rules` in `Routes.js`. Even the important ones like `indent`, `extensions` and so on.

2019-08-29 04:31 UTC, Hervera submitted a review, later dismissed
After creating an article, how can I see that article created and how can I update that Article? I do not know the slug to use

2019-08-29 06:59 UTC, niyoceles submitted a review, later dismissed
To create an article is ok, but after creating an article, the button of Edit and delete must be available on that page

2019-08-29 06:59 UTC, niyoceles commented on src/components/Routes.js
> +/* eslint-disable react/jsx-filename-extension */
@kodek-sleuth Kindly you must remove these (Eslint disabled) and put them in the `.eslintrc file`

2019-08-30 09:09 UTC, elemanhillary-zz submitted a review, later dismissed
PR title not sufficient and tests are not passing

2019-08-30 09:56 UTC, Hervera submitted a review, later dismissed
The coverage has dropped

2019-08-30 11:47 UTC, elemanhillary-zz requested changes
ready for merge

2019-08-30 11:48 UTC, elemanhillary-zz approved these changes
ready for merge

2019-08-30 11:49 UTC, niyoceles approved these changes
Can be merged

2019-08-30 11:52 UTC, IsaiahRn approved these changes

2019-08-30 14:53 UTC, merged