168066525 Users Should Be Able To Get The Landing Page Article Feed
andela/ah-92explorers-frontend pull request #22
Opened 2019-08-28 21:06 UTC by kodek-sleuth

#### What does this PR do?
Should enablea user to create and update an article
#### Description of Task to be completed
- Setup actions for making call to API
#### How should this be manually tested?
```
Run the following commands in your terminal after cloning the project
1. cd ah-92explorers-frontend
2. git checkout ft-fetch-article-feed-168066525
3. `npm i` to install all dependencies 
4. `npm run dev` and navigate to localhost:8080
```
#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?
[#168066525](https://www.pivotaltracker.com/story/show/168066525)
#### Screenshots (if appropriate)
#### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-09-02 08:28 UTC, elemanhillary-zz requested changes
Fix all files that need a new line at the EOF, please

2019-09-02 08:28 UTC, elemanhillary commented on .codeclimate.yml
> +    enabled: false
insert anew line at EOF, please

2019-09-02 08:34 UTC, elemanhillary-zz submitted a review, later dismissed
The feature is incomplete in the following ways:
- The homepage does not consist of articles, with there article clickable links
- The homepage is unresponsive
- Pagination does not exist
- And more....
Reach me for help we do this.

2019-09-02 09:22 UTC, Hervera submitted a review, later dismissed
Remove the merge conflicts

2019-09-03 07:51 UTC, elemanhillary-zz submitted a review, later dismissed
kindly implement the responsiveness on the page and let article clicks on images

2019-09-03 07:54 UTC, niyoceles submitted a review, later dismissed
Kindly remove all unused buttons  and add the link of sign up button

2019-09-03 08:24 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-09-03 08:42 UTC, niyoceles submitted a review, later dismissed
Feedback implemented well

2019-09-03 08:49 UTC, Hervera approved these changes
Ready to be merged

2019-09-03 08:57 UTC, Hervera requested changes
Squash the commits

2019-09-03 11:27 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-09-03 12:37 UTC, elemanhillary-zz submitted a review, later dismissed
ready for merge

2019-09-03 12:41 UTC, Hervera submitted a review, later dismissed
Ready to be merged

2019-09-03 12:43 UTC, niyoceles submitted a review, later dismissed
ready to be merged.

2019-09-03 13:44 UTC, Hervera approved these changes
Ready to be merged

2019-09-03 13:44 UTC, niyoceles approved these changes
ready for merged.

2019-09-03 13:46 UTC, elemanhillary-zz approved these changes
ready for merge

2019-09-03 13:47 UTC, merged