#166789969 Bookmark Articles for Reading Later
andela/ah-92explorers-frontend pull request #29
Opened 2019-09-08 11:05 UTC by IsaiahRn

#### What does this PR do?

#### Description of Task to be completed

#### How should this be manually tested?

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

#### Screenshots (if appropriate)

#### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I don't have more than 3 major commits on this PR

2019-09-11 09:54 UTC, niyoceles submitted a review, later dismissed
This PR can be merged, It is doing what expected to do.

2019-09-12 06:38 UTC, niyoceles submitted a review, later dismissed

2019-09-12 06:44 UTC, kodek-sleuth submitted a review, later dismissed
I failed to bookmark articles on the homepage, I think as a User I must be able to bookmark articles on the feed page.

2019-09-12 07:16 UTC, IsaiahRn commented
> I failed to bookmark articles on the homepage, I think as a User I must be able to bookmark articles on the feed page.

I am going to work on that it!

2019-09-12 13:26 UTC, elemanhillary-zz submitted a review, later dismissed
as a user am unable to bookmark more than 1 article, kindly fix the bug causing it.

2019-09-12 13:33 UTC, niyoceles submitted a review, later dismissed

2019-09-12 13:33 UTC, niyoceles commented on src/components/Articles/Feed.jsx
> -                <Link to={`/user-profile/${articles[0].author}`}><small className="profNameFeed pNFRF">{ articles[0].author }</small></Link>
Kindly don't remove this line, you can let this `user-profile` to separate the router of the user profile and other users.

2019-09-12 13:37 UTC, kodek-sleuth requested changes

2019-09-12 13:37 UTC, kodek-sleuth commented on src/components/Articles/Feed.jsx
> +    // const { feed } = this.props.article;
This convention of commenting out code was not accepted by the team, either remove those lines or actually use them

2019-09-12 13:41 UTC, kodek-sleuth submitted a review, later dismissed
I have still failed to bookmark articles on the homepage

2019-09-16 07:27 UTC, elemanhillary-zz submitted a review, later dismissed
kindly remove the alert boxes as @dmithamo instructed and its abit confusing to they eyes of a user when he/she bookmarked or unbookmarked an article

2019-09-16 08:27 UTC, kodek-sleuth submitted a review, later dismissed
Since this branch still has un commited changes, I failed to test it

2019-09-16 09:36 UTC, merged