#166789945 Setup React Redux
andela/ah-92explorers-frontend pull request #6
Opened 2019-08-14 20:39 UTC by kodek-sleuth

#### What does this PR do?
Should enable a user to highlight and comment on text in an article
#### Description of Task to be completed
- Create a model called highlights to store highlights and comments 
#### How should this be manually tested?
1. Clone Pull request and navigate to branch ch-setup-redux-166789945
2. Run command `npm i` in the terminal 
3. Run command `npm run dev` and navigate to `localhost:8080`
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166789945](https://www.pivotaltracker.com/story/show/166789945)
#### Screenshots (if appropriate)

#### Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I don't have more than 3 major commits on this PR

2019-08-14 22:28 UTC, elemanhillary-zz requested changes
kindly put back the linting scripts in `package.json` and fix all new line at EOF

2019-08-14 22:28 UTC, elemanhillary commented on public/index.html
> +    <title>React App</title>
title `Authors Haven` not `React App`

2019-08-14 22:28 UTC, elemanhillary commented on src/components/Routes.js
> +export default Routes;
new line at EOF

2019-08-15 19:58 UTC, IsaiahRn reviewed
Kindly, apply the changes requested by hillary?

2019-08-16 07:59 UTC, Hervera requested changes
Add a new blank line in each file

2019-08-16 08:15 UTC, niyoceles approved these changes

2019-08-16 08:15 UTC, Hervera approved these changes
Ready to be merged

2019-08-16 08:16 UTC, IsaiahRn approved these changes

2019-08-16 10:25 UTC, kipropbrian commented on .babelrc
> +          "@babel/plugin-proposal-class-properties"
Fix this, make it not an array. In future we can revert back.

2019-08-19 09:48 UTC, elemanhillary-zz requested changes
kindly implement the project structure in your project we had earlier agreed on. Every component under the component folder should have its own folder. Thanks

2019-08-19 12:49 UTC, niyoceles approved these changes

2019-08-19 12:56 UTC, IsaiahRn approved these changes

2019-08-19 13:04 UTC, Hervera approved these changes

2019-08-19 13:23 UTC, merged